# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


resources:
  - pipelines: pipeline
    project: echa-ecm
    source: IUCLID_Report_Templates
    branch: main



  - container: windows
    pipeline: self
    image: ubuntu-latest
    endpoint: Mark-R-R

    ports: 
    - 8080:80 # bind container port 80 to 8080 on the host machine
    - 6379 # bind container port 6379 to a random available port on the host machine
    volumes:
    - /src/dir:/dst/dir


  - repository: IUCLID_Report_Templates
    type: github
    name: echa-ecm/IUCLID_Report_Templates
    ref: main
    endpoint: Mark-R-R
 
    trigger:  # CI trigger for this repository, no CI trigger if skipped (only works for Azure Repos)
      branches:
        include: [ main ] # branch names which will trigger a build

trigger:
- main

pool:
  vmImage: ubuntu-latest
