# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

steps:
- publish: ${https://github.com/echa-ecm/IUCLID_Report_Templates.git}
  artifact: IUCLID_report_common_modules
  displayName: STRING
- checkout: self
  clean: true
  fetchDepth: 5
  lfs: true
  path: ${https://echa-ecm@dev.azure.com/echa-ecm/IUCLID_Report_Templates/_git/IUCLID_report_common_modules}\

trigger:
- main

pool:
  vmImage: ubuntu-latest
