# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


# Publish pipeline artifacts
# Publish (upload) a file or directory as a named artifact for the current run
- task: PublishPipelineArtifact@1
  inputs:
    #targetPath: $(https://github.com/echa-ecm/IUCLID_Report_Templates.git)
    #artifactName: 'drop' # Optional
    #artifactType: pipeline

steps:
- publish: $(/IUCLID_Report_Templates/_git/IUCLID_report_common_modules)/build 
  artifact: IUCLID_report_common_modules
  displayName: STRING
- checkout: self
  clean: true
  fetchDepth: 5
  lfs: true
  path: /home/vsts/work/1/s

trigger:
- main

pool:
  vmImage: ubuntu-latest
