# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

steps:
- publish: \echa-ecm\IUCLID_Report_Templates\IUCLID_report_common_modules\
  artifact: IUCLID_report_common_modules
  displayName: STRING
- checkout: self  # self represents the repo where the initial Azure Pipelines YAML file was found
  clean: true
  fetchDepth: 5
  lfs: true
  path: \github.com/echa-ecm\IUCLID_Report_Templates.git\

container:
trigger:
- main

pool:
  vmImage: ubuntu-latest
